spring.application.name=ecommerce

# Enable Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2